In [1]:
import pandas as pd
from tweetbench.expirements import gather, make_table, run
from tweetbench.notebook_loader import NotebookLoader
from tweetbench.data import get_splits

running importer


In [2]:
expirements = gather()

importing Jupyter notebook from /Users/amagill/school/ds/store/a-m730/Project/source/expirements/baseline.ipynb
importing Jupyter notebook from /Users/amagill/school/ds/store/a-m730/Project/source/expirements/001.ipynb


In [3]:
splits = get_splits()

reading in data...


In [4]:
results = []
for split in splits:
    for expirement in expirements:
        rdf, X_test, predictions, probabilities = run(expirement, split)
        results.append(rdf)

________________________________________________________________________________
Training: 
{'classifier': 'LogisticRegression(analyzer=word, binary=False, '
               "decode_error=strict, dtype=<class 'numpy.int64'>, "
               'encoding=utf-8, input=content, lowercase=False, max_df=1.0, '
               'max_features=None, min_df=1, ngram_range=(1, 1), '
               'preprocessor=None, stop_words=None, strip_accents=None, '
               'token_pattern=(?u)\\b\\w\\w+\\b, tokenizer=None, '
               'vocabulary=None, C=1.0, class_weight=None, dual=False, '
               'fit_intercept=True, intercept_scaling=1, l1_ratio=None, '
               'max_iter=100, multi_class=auto, n_jobs=None, penalty=l2, '
               'random_state=None, solver=lbfgs, tol=0.0001, verbose=0, '
               'warm_start=False, )',
 'vectorizer': 'CountVectorizer(analyzer=word, binary=False, '
               "decode_error=strict, dtype=<class 'numpy.int64'>, "
               'encodin

/Users/amagill/.envs/38/fakenews/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


train time: 1.463s
test time:  0.111s

mcc:   0.433,   prec:   0.582,   rec:   0.528,   acc:   0.766

confusion matrix:
[[119  22  87]
 [ 26  17  78]
 [ 48  17 776]]


________________________________________________________________________________
Training: 
{'classifier': 'LogisticRegression(analyzer=word, binary=False, '
               "decode_error=strict, dtype=<class 'numpy.int64'>, "
               'encoding=utf-8, input=content, lowercase=True, max_df=1.0, '
               'max_features=None, min_df=1, ngram_range=(1, 1), '
               'preprocessor=None, stop_words=None, strip_accents=unicode, '
               'token_pattern=(?u)\\b\\w\\w+\\b, tokenizer=None, '
               'vocabulary=None, C=0.9, class_weight={1: 0.4, 2: 0.4, 3: 0.2}, '
               'dual=False, fit_intercept=True, intercept_scaling=1, '
               'l1_ratio=None, max_iter=2000, multi_class=ovr, n_jobs=None, '
               'penalty=l2, random_state=None, solver=saga, tol=0.0001, '
              

/Users/amagill/.envs/38/fakenews/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


train time: 1.524s
test time:  0.111s

mcc:   0.402,   prec:   0.591,   rec:   0.528,   acc:   0.742

confusion matrix:
[[114  15  92]
 [ 31  24  94]
 [ 54  21 745]]


________________________________________________________________________________
Training: 
{'classifier': 'LogisticRegression(analyzer=word, binary=False, '
               "decode_error=strict, dtype=<class 'numpy.int64'>, "
               'encoding=utf-8, input=content, lowercase=True, max_df=1.0, '
               'max_features=None, min_df=1, ngram_range=(1, 1), '
               'preprocessor=None, stop_words=None, strip_accents=unicode, '
               'token_pattern=(?u)\\b\\w\\w+\\b, tokenizer=None, '
               'vocabulary=None, C=0.9, class_weight={1: 0.4, 2: 0.4, 3: 0.2}, '
               'dual=False, fit_intercept=True, intercept_scaling=1, '
               'l1_ratio=None, max_iter=2000, multi_class=ovr, n_jobs=None, '
               'penalty=l2, random_state=None, solver=saga, tol=0.0001, '
              

/Users/amagill/.envs/38/fakenews/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


train time: 1.618s
test time:  0.120s

mcc:   0.410,   prec:   0.604,   rec:   0.533,   acc:   0.745

confusion matrix:
[[109  19 102]
 [ 29  30  85]
 [ 47  22 747]]


________________________________________________________________________________
Training: 
{'classifier': 'LogisticRegression(analyzer=word, binary=False, '
               "decode_error=strict, dtype=<class 'numpy.int64'>, "
               'encoding=utf-8, input=content, lowercase=True, max_df=1.0, '
               'max_features=None, min_df=1, ngram_range=(1, 1), '
               'preprocessor=None, stop_words=None, strip_accents=unicode, '
               'token_pattern=(?u)\\b\\w\\w+\\b, tokenizer=None, '
               'vocabulary=None, C=0.9, class_weight={1: 0.4, 2: 0.4, 3: 0.2}, '
               'dual=False, fit_intercept=True, intercept_scaling=1, '
               'l1_ratio=None, max_iter=2000, multi_class=ovr, n_jobs=None, '
               'penalty=l2, random_state=None, solver=saga, tol=0.0001, '
              

/Users/amagill/.envs/38/fakenews/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


train time: 1.661s
test time:  0.125s

mcc:   0.375,   prec:   0.579,   rec:   0.515,   acc:   0.725

confusion matrix:
[[106  18  97]
 [ 34  26 100]
 [ 60  18 731]]


________________________________________________________________________________
Training: 
{'classifier': 'LogisticRegression(analyzer=word, binary=False, '
               "decode_error=strict, dtype=<class 'numpy.int64'>, "
               'encoding=utf-8, input=content, lowercase=True, max_df=1.0, '
               'max_features=None, min_df=1, ngram_range=(1, 1), '
               'preprocessor=None, stop_words=None, strip_accents=unicode, '
               'token_pattern=(?u)\\b\\w\\w+\\b, tokenizer=None, '
               'vocabulary=None, C=0.9, class_weight={1: 0.4, 2: 0.4, 3: 0.2}, '
               'dual=False, fit_intercept=True, intercept_scaling=1, '
               'l1_ratio=None, max_iter=2000, multi_class=ovr, n_jobs=None, '
               'penalty=l2, random_state=None, solver=saga, tol=0.0001, '
              

/Users/amagill/.envs/38/fakenews/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


train time: 1.570s
test time:  0.116s

mcc:   0.388,   prec:   0.559,   rec:   0.520,   acc:   0.739

confusion matrix:
[[106  23  83]
 [ 33  23  90]
 [ 54  27 751]]


________________________________________________________________________________
Training: 
{'classifier': 'LogisticRegression(analyzer=word, binary=False, '
               "decode_error=strict, dtype=<class 'numpy.int64'>, "
               'encoding=utf-8, input=content, lowercase=True, max_df=1.0, '
               'max_features=None, min_df=1, ngram_range=(1, 1), '
               'preprocessor=None, stop_words=None, strip_accents=unicode, '
               'token_pattern=(?u)\\b\\w\\w+\\b, tokenizer=None, '
               'vocabulary=None, C=0.9, class_weight={1: 0.4, 2: 0.4, 3: 0.2}, '
               'dual=False, fit_intercept=True, intercept_scaling=1, '
               'l1_ratio=None, max_iter=2000, multi_class=ovr, n_jobs=None, '
               'penalty=l2, random_state=None, solver=saga, tol=0.0001, '
              

In [5]:
results_df = pd.concat(results)
results_df = results_df.groupby(['expirement']).mean()
results_df = results_df.sort_index(ascending=True)

In [6]:
make_table(results_df)